### ISSUE TITLE
not working, several errors

### ISSUE THREAD

**Issue by ealcober** [yjose/twitter-bot#8]
Some of the characteristics has changed from your develoment to present. I post the logs. Your code actually no works.

2019-01-04T14:00:59.045056+00:00 heroku[worker.1]: Process exited with status 1

2019-01-04T14:00:58.968074+00:00 app[worker.1]: events.js:167

2019-01-04T14:00:58.968099+00:00 app[worker.1]:       throw er; // Unhandled 'error' event

2019-01-04T14:00:58.968100+00:00 app[worker.1]:       ^

2019-01-04T14:00:58.968102+00:00 app[worker.1]: 

2019-01-04T14:00:58.968103+00:00 app[worker.1]: Error: Bad Twitter streaming request: 404

2019-01-04T14:00:58.968105+00:00 app[worker.1]:     at Object.exports.makeTwitError (/app/node_modules/twit/lib/helpers.js:74:13)

2019-01-04T14:00:58.968106+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:96:29)

2019-01-04T14:00:58.968107+00:00 app[worker.1]:     at Request.emit (events.js:187:15)

2019-01-04T14:00:58.968108+00:00 app[worker.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)

2019-01-04T14:00:58.968109+00:00 app[worker.1]:     at Object.onceWrapper (events.js:273:13)

2019-01-04T14:00:58.968111+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:187:15)

2019-01-04T14:00:58.968112+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1094:12)

2019-01-04T14:00:58.968114+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)

2019-01-04T14:00:58.968115+00:00 app[worker.1]: Emitted 'error' event at:

2019-01-04T14:00:58.968117+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:99:14)

2019-01-04T14:00:58.968118+00:00 app[worker.1]:     at Request.emit (events.js:187:15)

2019-01-04T14:00:58.968119+00:00 app[worker.1]:     [... lines matching original stack trace ...]

2019-01-04T14:00:58.968120+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)

2019-01-04T14:00:48.755963+00:00 app[api]: Scaled to web@0:Free worker@0:Free by user community.salomons@gmail.com

2019-01-04T14:00:49.775234+00:00 app[api]: Scaled to web@0:Free worker@1:Free by user community.salomons@gmail.com

2019-01-04T14:01:01.397695+00:00 heroku[worker.1]: Starting process with command `node index.js`

2019-01-04T14:01:02.020100+00:00 heroku[worker.1]: State changed from starting to up

2019-01-04T14:01:04.936613+00:00 app[worker.1]: App started successfully 🙌🙌

2019-01-04T14:01:04.939232+00:00 app[worker.1]: Start Sending Auto Direct Message 🚀🚀🚀

2019-01-04T14:01:05.624418+00:00 heroku[worker.1]: State changed from up to crashed

2019-01-04T14:01:05.515291+00:00 app[worker.1]: events.js:167

2019-01-04T14:01:05.515314+00:00 app[worker.1]:       throw er; // Unhandled 'error' event

2019-01-04T14:01:05.515316+00:00 app[worker.1]:       ^

2019-01-04T14:01:05.515317+00:00 app[worker.1]: 

2019-01-04T14:01:05.515318+00:00 app[worker.1]: Error: Bad Twitter streaming request: 404

2019-01-04T14:01:05.515320+00:00 app[worker.1]:     at Object.exports.makeTwitError (/app/node_modules/twit/lib/helpers.js:74:13)

2019-01-04T14:01:05.515321+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:96:29)

2019-01-04T14:01:05.515322+00:00 app[worker.1]:     at Request.emit (events.js:187:15)

2019-01-04T14:01:05.515324+00:00 app[worker.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)

2019-01-04T14:01:05.515325+00:00 app[worker.1]:     at Object.onceWrapper (events.js:273:13)

2019-01-04T14:01:05.515326+00:00 app[worker.1]:     at IncomingMessage.emit (events.js:187:15)

2019-01-04T14:01:05.515328+00:00 app[worker.1]:     at endReadableNT (_stream_readable.js:1094:12)

2019-01-04T14:01:05.515329+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)

2019-01-04T14:01:05.515331+00:00 app[worker.1]: Emitted 'error' event at:

2019-01-04T14:01:05.515332+00:00 app[worker.1]:     at Request.<anonymous> (/app/node_modules/twit/lib/streaming-api-connection.js:99:14)

2019-01-04T14:01:05.515334+00:00 app[worker.1]:     at Request.emit (events.js:187:15)

2019-01-04T14:01:05.515335+00:00 app[worker.1]:     [... lines matching original stack trace ...]

2019-01-04T14:01:05.515336+00:00 app[worker.1]:     at process._tickCallback (internal/process/next_tick.js:63:19)

2019-01-04T14:01:05.604165+00:00 heroku[worker.1]: Process exited with status 1

**Comment by Tjird** [comment]
Same issue bad streaming request 404 @yjose

**Comment by Tjird** [comment]
```
 node ./index.js
App started successfully 🙌🙌
Start Sending Auto Direct Message 🚀🚀🚀
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Bad Twitter streaming request: 404
    at Object.exports.makeTwitError (/root/newtwitbot/twitter-bot/node_modules/twit/lib/helpers.js:74:13)
    at Request.<anonymous> (/root/newtwitbot/twitter-bot/node_modules/twit/lib/streaming-api-connection.js:96:29)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (/root/newtwitbot/twitter-bot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Request.<anonymous> (/root/newtwitbot/twitter-bot/node_modules/twit/lib/streaming-api-connection.js:99:14)
    at Request.emit (events.js:187:15)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by ealcober** [comment]
I think this user has left unnattended this project.

**Comment by Tjird** [comment]
I think it also... The package twit that this project is using is also not working anymore.
